// Fichier GÉNÉRÉ par tauri-specta — ne jamais éditer à la main.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**
	 *  Dossier personnel absolu — les chemins des plists launchd ne passent pas
	 *  par un shell, donc pas de $HOME/~ possible dans les suggestions.
	 */
	homeDir: () => __TAURI_INVOKE<string>("home_dir"),
	listJobs: (backend: BackendKind) => typedError<Job[], ApiError>(__TAURI_INVOKE("list_jobs", { backend })),
	getJob: (backend: BackendKind, id: string) => typedError<Job, ApiError>(__TAURI_INVOKE("get_job", { backend, id })),
	createJob: (backend: BackendKind, spec: JobSpec) => typedError<string, ApiError>(__TAURI_INVOKE("create_job", { backend, spec })),
	updateJob: (backend: BackendKind, id: string, spec: JobSpec) => typedError<null, ApiError>(__TAURI_INVOKE("update_job", { backend, id, spec })),
	deleteJob: (backend: BackendKind, id: string) => typedError<null, ApiError>(__TAURI_INVOKE("delete_job", { backend, id })),
	setJobEnabled: (backend: BackendKind, id: string, enabled: boolean) => typedError<null, ApiError>(__TAURI_INVOKE("set_job_enabled", { backend, id, enabled })),
	/**
	 *  Exécution à la demande (§5.5 / §6.6) — potentiellement longue, toujours hors
	 *  du thread principal.
	 */
	runJob: (backend: BackendKind, id: string) => typedError<RunResult, ApiError>(__TAURI_INVOKE("run_job", { backend, id })),
	runDiagnostics: (backend: BackendKind) => typedError<Diagnostic[], ApiError>(__TAURI_INVOKE("run_diagnostics", { backend })),
	previewSchedule: (schedule: ScheduleInfo) => __TAURI_INVOKE<SchedulePreview>("preview_schedule", { schedule }),
	/**
	 *  Visionneuse de logs (§8.1) : dernières lignes d'un fichier de log
	 *  launchd (tail simple, pas de suivi live au MVP). `$HOME` accepté en tête
	 *  de chemin (convention des suggestions de journal).
	 */
	readLogTail: (path: string) => typedError<string, ApiError>(__TAURI_INVOKE("read_log_tail", { path })),
};

/* Types */
/**
 *  Forme sérialisable exposée à l'IPC (§4) : `code` stable pour la traduction
 *  côté frontend (§8.2), `message` = fallback technique.
 */
export type ApiError = {
	code: string,
	message: string,
	detail: string | null,
};

export type BackendKind = "cron" | "launchd";

/**  Une entrée de StartCalendarInterval. Champs absents = "toutes les valeurs". */
export type CalendarEntry = {
	minute: number | null,
	hour: number | null,
	day: number | null,
	/**  0-7, 0 et 7 = dimanche (normalisé à 0 au parsing, §11). */
	weekday: number | null,
	month: number | null,
};

export type CronJobSpec = {
	/**  Expression 5 champs (l'éditeur ne crée pas de @-raccourcis, §5.1). */
	schedule: string,
	command: string,
	/**  Écrit en commentaire `# name: ...` sur la ligne précédente (§5.1). */
	name: string | null,
};

/**
 *  Un check de diagnostic (§8). `code` est stable : le frontend le traduit (§8.2) ;
 *  `detail` porte du contexte brut non traduisible (chemin, stderr...).
 */
export type Diagnostic = {
	severity: DiagnosticSeverity,
	code: string,
	detail: string | null,
};

export type DiagnosticSeverity = "ok" | "warning" | "error";

/**  Modèle commun en lecture (§3.1). */
export type Job = {
	id: string,
	backend: BackendKind,
	/**  Nom d'affichage : name s'il existe, sinon commande tronquée. */
	label: string,
	/**  Nom explicite (cron : commentaire `# name:`) — None si absent. */
	name: string | null,
	command: string,
	schedule: ScheduleInfo,
	scheduleRaw: string,
	enabled: boolean,
	/**  5 prochaines occurrences, RFC3339 avec offset local. Vide si non calculable. */
	nextRuns: string[],
	status: JobStatus,
	/**  launchd : extrait de `launchctl print` (défensif). cron : None. */
	lastExitCode: number | null,
	/**  launchd : label préfixé com.ubercron. — cron : toujours true (§3.1). */
	managed: boolean,
	/**
	 *  launchd : spec reconstruite pour l'éditeur et la visionneuse de logs.
	 *  None pour cron, et pour les agents sans schedule (non éditables via le
	 *  formulaire — on ne donne pas accidentellement un schedule à un daemon
	 *  KeepAlive).
	 */
	launchdSpec: LaunchdJobSpec | null,
};

/**  Spécification d'édition, par backend — PAS de formulaire unifié (§3.3). */
export type JobSpec = { type: "cron"; value: CronJobSpec } | { type: "launchd"; value: LaunchdJobSpec };

export type JobStatus = 
/**  launchd : process en cours d'exécution. */
"running" | 
/**  launchd : chargé dans le domaine gui, pas en cours d'exécution. */
"loaded" | 
/**  launchd : non chargé. */
"notloaded" | 
/**  cron : pas de notion d'état runtime. */
"static" | 
/**  launchd : `launchctl print` inexploitable (parsing défensif, §6.2). */
"unknown";

/**  Mode de commande launchd (§6.3) : wrapper shell par défaut, ou argv explicite. */
export type LaunchdCommand = { type: "shellWrapper"; value: string } | { type: "argv"; value: string[] };

export type LaunchdJobSpec = {
	label: string,
	command: LaunchdCommand,
	schedule: LaunchdSchedule,
	runAtLoad: boolean,
	stdoutPath: string | null,
	stderrPath: string | null,
};

export type LaunchdSchedule = { type: "calendarIntervals"; value: CalendarEntry[] } | { type: "interval"; value: number };

/**  Résultat d'un "Exécuter maintenant" (§4). */
export type RunResult = 
/**  cron : exécution directe terminée. */
{ type: "completed"; value: {
	exitCode: number,
	stdoutTail: string,
	stderrTail: string,
} } | 
/**  launchd : kickstart asynchrone — consulter statut/logs. */
{ type: "started" };

/**  Représentation structurée du schedule — le frontend en dérive la phrase humaine (§3.1). */
export type ScheduleInfo = 
/**  Expression 5 champs ou @-raccourci (@daily, @reboot...). */
{ type: "cronExpr"; value: string } | { type: "calendarIntervals"; value: CalendarEntry[] } | 
/**  StartInterval en secondes. */
{ type: "interval"; value: number } | 
/**  launchd sans schedule (KeepAlive, WatchPaths...) — DECISIONS 2026-07-10. */
{ type: "none" };

/**
 *  Aperçu live du formulaire (§7). La phrase humaine est calculée côté frontend ;
 *  ici uniquement validité + prochaines occurrences.
 */
export type SchedulePreview = {
	valid: boolean,
	nextRuns: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

